LibEndian: LittleEndian Class Reference
LittleEndian Class Reference
#include <LittleEndian.hpp>
Static Public Member Functions
static uint8_t GET_UINT8 (const uint8_t *buf)
static uint16_t GET_UINT16 (const uint8_t *buf)
static uint32_t GET_UINT32 (const uint8_t *buf)
static uint64_t GET_UINT48 (const uint8_t *buf)
static uint64_t GET_UINT64 (const uint8_t *buf)
static int8_t GET_INT8 (const uint8_t *buf)
static int16_t GET_INT16 (const uint8_t *buf)
static int32_t GET_INT32 (const uint8_t *buf)
static int64_t GET_INT48 (const uint8_t *buf)
static int64_t GET_INT64 (const uint8_t *buf)
static float GET_FLOAT32 (const uint8_t *buf)
static double GET_FLOAT64 (const uint8_t *buf)
static uint8_t GET_UINT8 (const uint8_t *buf, const int offset)
static uint16_t GET_UINT16 (const uint8_t *buf, const int offset)
static uint32_t GET_UINT32 (const uint8_t *buf, const int offset)
static uint64_t GET_UINT48 (const uint8_t *buf, const int offset)
static uint64_t GET_UINT64 (const uint8_t *buf, const int offset)
static int8_t GET_INT8 (const uint8_t *buf, const int offset)
static int16_t GET_INT16 (const uint8_t *buf, const int offset)
static int32_t GET_INT32 (const uint8_t *buf, const int offset)
static int64_t GET_INT48 (const uint8_t *buf, const int offset)
static int64_t GET_INT64 (const uint8_t *buf, const int offset)
static float GET_FLOAT32 (const uint8_t *buf, const int offset)
static double GET_FLOAT64 (const uint8_t *buf, const int offset)
static void SET_UINT8 (uint8_t *buf, const uint8_t val)
static void SET_UINT16 (uint8_t *buf, const uint16_t val)
static void SET_UINT32 (uint8_t *buf, const uint32_t val)
static void SET_UINT48 (uint8_t *buf, const uint64_t val)
static void SET_UINT64 (uint8_t *buf, const uint64_t val)
static void SET_INT8 (uint8_t *buf, const int8_t val)
static void SET_INT16 (uint8_t *buf, const int16_t val)
static void SET_INT32 (uint8_t *buf, const int32_t val)
static void SET_INT48 (uint8_t *buf, const int64_t val)
static void SET_INT64 (uint8_t *buf, const int64_t val)
static void SET_FLOAT32 (uint8_t *buf, const float val)
static void SET_FLOAT64 (uint8_t *buf, const double val)
static void SET_UINT8 (uint8_t *buf, const int offset, const uint8_t val)
static void SET_UINT16 (uint8_t *buf, const int offset, const uint16_t val)
static void SET_UINT32 (uint8_t *buf, const int offset, const uint32_t val)
static void SET_UINT48 (uint8_t *buf, const int offset, const uint64_t val)
static void SET_UINT64 (uint8_t *buf, const int offset, const uint64_t val)
static void SET_INT8 (uint8_t *buf, const int offset, const int8_t val)
static void SET_INT16 (uint8_t *buf, const int offset, const int16_t val)
static void SET_INT32 (uint8_t *buf, const int offset, const int32_t val)
static void SET_INT48 (uint8_t *buf, const int offset, const int64_t val)
static void SET_INT64 (uint8_t *buf, const int offset, const int64_t val)
static void SET_FLOAT32 (uint8_t *buf, const int offset, const float val)
static void SET_FLOAT64 (uint8_t *buf, const int offset, const double val)
static void SET_UINT8 (uint8_t *buf, const int offset, const uint8_t val, int &length)
static void SET_UINT16 (uint8_t *buf, const int offset, const uint16_t val, int &length)
static void SET_UINT32 (uint8_t *buf, const int offset, const uint32_t val, int &length)
static void SET_UINT48 (uint8_t *buf, const int offset, const uint64_t val, int &length)
static void SET_UINT64 (uint8_t *buf, const int offset, const uint64_t val, int &length)
static void SET_INT8 (uint8_t *buf, const int offset, const int8_t val, int &length)
static void SET_INT16 (uint8_t *buf, const int offset, const int16_t val, int &length)
static void SET_INT32 (uint8_t *buf, const int offset, const int32_t val, int &length)
static void SET_INT48 (uint8_t *buf, const int offset, const int64_t val, int &length)
static void SET_INT64 (uint8_t *buf, const int offset, const int64_t val, int &length)
static void SET_FLOAT32 (uint8_t *buf, const int offset, const float val, int &length)
static void SET_FLOAT64 (uint8_t *buf, const int offset, const double val, int &length)
static uint8_t GET_UINT8 (const char *buf)
static uint16_t GET_UINT16 (const char *buf)
static uint32_t GET_UINT32 (const char *buf)
static uint64_t GET_UINT48 (const char *buf)
static uint64_t GET_UINT64 (const char *buf)
static int8_t GET_INT8 (const char *buf)
static int16_t GET_INT16 (const char *buf)
static int32_t GET_INT32 (const char *buf)
static int64_t GET_INT48 (const char *buf)
static int64_t GET_INT64 (const char *buf)
static float GET_FLOAT32 (const char *buf)
static double GET_FLOAT64 (const char *buf)
static uint8_t GET_UINT8 (const char *buf, const int offset)
static uint16_t GET_UINT16 (const char *buf, const int offset)
static uint32_t GET_UINT32 (const char *buf, const int offset)
static uint64_t GET_UINT48 (const char *buf, const int offset)
static uint64_t GET_UINT64 (const char *buf, const int offset)
static int8_t GET_INT8 (const char *buf, const int offset)
static int16_t GET_INT16 (const char *buf, const int offset)
static int32_t GET_INT32 (const char *buf, const int offset)
static int64_t GET_INT48 (const char *buf, const int offset)
static int64_t GET_INT64 (const char *buf, const int offset)
static float GET_FLOAT32 (const char *buf, const int offset)
static double GET_FLOAT64 (const char *buf, const int offset)
static void SET_UINT8 (char *buf, const uint8_t val)
static void SET_UINT16 (char *buf, const uint16_t val)
static void SET_UINT32 (char *buf, const uint32_t val)
static void SET_UINT48 (char *buf, const uint64_t val)
static void SET_UINT64 (char *buf, const uint64_t val)
static void SET_INT8 (char *buf, const int8_t val)
static void SET_INT16 (char *buf, const int16_t val)
static void SET_INT32 (char *buf, const int32_t val)
static void SET_INT48 (char *buf, const int64_t val)
static void SET_INT64 (char *buf, const int64_t val)
static void SET_FLOAT32 (char *buf, const float val)
static void SET_FLOAT64 (char *buf, const double val)
static void SET_UINT8 (char *buf, const int offset, const uint8_t val)
static void SET_UINT16 (char *buf, const int offset, const uint16_t val)
static void SET_UINT32 (char *buf, const int offset, const uint32_t val)
static void SET_UINT48 (char *buf, const int offset, const uint64_t val)
static void SET_UINT64 (char *buf, const int offset, const uint64_t val)
static void SET_INT8 (char *buf, const int offset, const int8_t val)
static void SET_INT16 (char *buf, const int offset, const int16_t val)
static void SET_INT32 (char *buf, const int offset, const int32_t val)
static void SET_INT48 (char *buf, const int offset, const int64_t val)
static void SET_INT64 (char *buf, const int offset, const int64_t val)
static void SET_FLOAT32 (char *buf, const int offset, const float val)
static void SET_FLOAT64 (char *buf, const int offset, const double val)
static void SET_UINT8 (char *buf, const int offset, const uint8_t val, int &length)
static void SET_UINT16 (char *buf, const int offset, const uint16_t val, int &length)
static void SET_UINT32 (char *buf, const int offset, const uint32_t val, int &length)
static void SET_UINT48 (char *buf, const int offset, const uint64_t val, int &length)
static void SET_UINT64 (char *buf, const int offset, const uint64_t val, int &length)
static void SET_INT8 (char *buf, const int offset, const int8_t val, int &length)
static void SET_INT16 (char *buf, const int offset, const int16_t val, int &length)
static void SET_INT32 (char *buf, const int offset, const int32_t val, int &length)
static void SET_INT48 (char *buf, const int offset, const int64_t val, int &length)
static void SET_INT64 (char *buf, const int offset, const int64_t val, int &length)
static void SET_FLOAT32 (char *buf, const int offset, const float val, int &length)
static void SET_FLOAT64 (char *buf, const int offset, const double val, int &length)
Additional Inherited Members
Static Public Attributes inherited from LibEndian
static const uint8_t UINT8_SIZE = 1
static const uint8_t UINT16_SIZE = 2
static const uint8_t UINT32_SIZE = 4
static const uint8_t UINT48_SIZE = 6
static const uint8_t UINT64_SIZE = 8
static const uint8_t INT8_SIZE = 1
static const uint8_t INT16_SIZE = 2
static const uint8_t INT32_SIZE = 4
static const uint8_t INT48_SIZE = 6
static const uint8_t INT64_SIZE = 8
static const uint8_t FLOAT32_SIZE = 4
static const uint8_t FLOAT64_SIZE = 8
Detailed Description
Serialize binary data in little endian way
Member Function Documentation
GET_FLOAT32() [1/4]
static float LittleEndian::GET_FLOAT32 (const uint8_t * buf) inline static
Deserialize an float from buffer
Parameters
buf Pointer to the float
Returns
The deserialized data
GET_FLOAT32() [2/4]
static float LittleEndian::GET_FLOAT32 (const uint8_t * buf, const int offset) inline static
Deserialize an float from buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer to access to an float* (in bytes)
Returns
The deserialized data
References GET_FLOAT32().
Referenced by GET_FLOAT32().
GET_FLOAT32() [3/4]
static float LittleEndian::GET_FLOAT32 (const char * buf) inline static
Deserialize an float from buffer
Parameters
buf Pointer to the float
Returns
The deserialized data
GET_FLOAT32() [4/4]
static float LittleEndian::GET_FLOAT32 (const char * buf, const int offset) inline static
Deserialize an float from buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer to access to an float* (in bytes)
Returns
The deserialized data
References GET_FLOAT32().
Referenced by GET_FLOAT32().
GET_FLOAT64() [1/4]
static double LittleEndian::GET_FLOAT64 (const uint8_t * buf) inline static
Deserialize an double from buffer
Parameters
buf Pointer to the double
Returns
The deserialized data
GET_FLOAT64() [2/4]
static double LittleEndian::GET_FLOAT64 (const uint8_t * buf, const int offset) inline static
Deserialize an double from buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer to access to an double (in bytes)
Returns
The deserialized data
References GET_FLOAT64().
Referenced by GET_FLOAT64().
GET_FLOAT64() [3/4]
static double LittleEndian::GET_FLOAT64 (const char * buf) inline static
Deserialize an double from buffer
Parameters
buf Pointer to the double
Returns
The deserialized data
GET_FLOAT64() [4/4]
static double LittleEndian::GET_FLOAT64 (const char * buf, const int offset) inline static
Deserialize an double from buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer to access to an double (in bytes)
Returns
The deserialized data
References GET_FLOAT64().
Referenced by GET_FLOAT64().
GET_INT16() [1/4]
static int16_t LittleEndian::GET_INT16 (const uint8_t * buf) inline static
Deserialize an int16_t from buffer
Parameters
buf Pointer to the int16_t
Returns
The deserialized data
GET_INT16() [2/4]
static int16_t LittleEndian::GET_INT16 (const uint8_t * buf, const int offset) inline static
Deserialize an int16_t from buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer to access to an int16_t* (in bytes)
Returns
The deserialized data
References GET_INT16().
Referenced by GET_INT16().
GET_INT16() [3/4]
static int16_t LittleEndian::GET_INT16 (const char * buf) inline static
Deserialize an int16_t from buffer
Parameters
buf Pointer to the int16_t
Returns
The deserialized data
GET_INT16() [4/4]
static int16_t LittleEndian::GET_INT16 (const char * buf, const int offset) inline static
Deserialize an int16_t from buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer to access to an int16_t* (in bytes)
Returns
The deserialized data
References GET_INT16().
Referenced by GET_INT16().
GET_INT32() [1/4]
static int32_t LittleEndian::GET_INT32 (const uint8_t * buf) inline static
Deserialize an int32_t from buffer
Parameters
buf Pointer to the int32_t
Returns
The deserialized data
GET_INT32() [2/4]
static int32_t LittleEndian::GET_INT32 (const uint8_t * buf, const int offset) inline static
Deserialize an int32_t from buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer to access to an int32_t* (in bytes)
Returns
The deserialized data
References GET_INT32().
Referenced by GET_INT32().
GET_INT32() [3/4]
static int32_t LittleEndian::GET_INT32 (const char * buf) inline static
Deserialize an int32_t from buffer
Parameters
buf Pointer to the int32_t
Returns
The deserialized data
GET_INT32() [4/4]
static int32_t LittleEndian::GET_INT32 (const char * buf, const int offset) inline static
Deserialize an int32_t from buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer to access to an int32_t* (in bytes)
Returns
The deserialized data
References GET_INT32().
Referenced by GET_INT32().
GET_INT48() [1/4]
static int64_t LittleEndian::GET_INT48 (const uint8_t * buf) inline static
Deserialize an int48_t from buffer.
Note
It is return on a int64_t for conveniance
Parameters
buf Pointer to the uint48_t
Returns
The deserialized data
GET_INT48() [2/4]
static int64_t LittleEndian::GET_INT48 (const uint8_t * buf, const int offset) inline static
Deserialize an int48_t from buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer to access to an int48_t* (in bytes)
Note
Store in a int64_t for conveniance
Returns
The deserialized data
References GET_INT48().
Referenced by GET_INT48().
GET_INT48() [3/4]
static int64_t LittleEndian::GET_INT48 (const char * buf) inline static
Deserialize an int48_t from buffer.
Note
It is return on a int64_t for conveniance
Parameters
buf Pointer to the uint48_t
Returns
The deserialized data
GET_INT48() [4/4]
static int64_t LittleEndian::GET_INT48 (const char * buf, const int offset) inline static
Deserialize an int48_t from buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer to access to an int48_t* (in bytes)
Note
Store in a int64_t for conveniance
Returns
The deserialized data
References GET_INT48().
Referenced by GET_INT48().
GET_INT64() [1/4]
static int64_t LittleEndian::GET_INT64 (const uint8_t * buf) inline static
Deserialize an int64_t from buffer
Parameters
buf Pointer to the int64_t
Returns
The deserialized data
GET_INT64() [2/4]
static int64_t LittleEndian::GET_INT64 (const uint8_t * buf, const int offset) inline static
Deserialize an int64_t from buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer to access to an int64_t* (in bytes)
Returns
The deserialized data
References GET_INT64().
Referenced by GET_INT64().
GET_INT64() [3/4]
static int64_t LittleEndian::GET_INT64 (const char * buf) inline static
Deserialize an int64_t from buffer
Parameters
buf Pointer to the int64_t
Returns
The deserialized data
GET_INT64() [4/4]
static int64_t LittleEndian::GET_INT64 (const char * buf, const int offset) inline static
Deserialize an int64_t from buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer to access to an int64_t* (in bytes)
Returns
The deserialized data
References GET_INT64().
Referenced by GET_INT64().
GET_INT8() [1/4]
static int8_t LittleEndian::GET_INT8 (const uint8_t * buf) inline static
Deserialize an int8_t from buffer
Parameters
buf Pointer to the int8_t
Returns
The deserialized data
GET_INT8() [2/4]
static int8_t LittleEndian::GET_INT8 (const uint8_t * buf, const int offset) inline static
Deserialize an int8_t from buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer to access to an int8_t* (in bytes)
Returns
The deserialized data
References GET_INT8().
Referenced by GET_INT8().
GET_INT8() [3/4]
static int8_t LittleEndian::GET_INT8 (const char * buf) inline static
Deserialize an int8_t from buffer
Parameters
buf Pointer to the int8_t
Returns
The deserialized data
GET_INT8() [4/4]
static int8_t LittleEndian::GET_INT8 (const char * buf, const int offset) inline static
Deserialize an int8_t from buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer to access to an int8_t* (in bytes)
Returns
The deserialized data
References GET_INT8().
Referenced by GET_INT8().
GET_UINT16() [1/4]
static uint16_t LittleEndian::GET_UINT16 (const uint8_t * buf) inline static
Deserialize an uint16_t from buffer
Parameters
buf Pointer to the uint16_t
Returns
The deserialized data
GET_UINT16() [2/4]
static uint16_t LittleEndian::GET_UINT16 (const uint8_t * buf, const int offset) inline static
Deserialize an uint16_t from buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer to access to an uint16_t* (in bytes)
Returns
The deserialized data
References GET_UINT16().
Referenced by GET_UINT16().
GET_UINT16() [3/4]
static uint16_t LittleEndian::GET_UINT16 (const char * buf) inline static
Deserialize an uint16_t from buffer
Parameters
buf Pointer to the uint16_t
Returns
The deserialized data
References GET_UINT16().
Referenced by GET_UINT16().
GET_UINT16() [4/4]
static uint16_t LittleEndian::GET_UINT16 (const char * buf, const int offset) inline static
Deserialize an uint16_t from buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer to access to an uint16_t* (in bytes)
Returns
The deserialized data
References GET_UINT16().
Referenced by GET_UINT16().
GET_UINT32() [1/4]
static uint32_t LittleEndian::GET_UINT32 (const uint8_t * buf) inline static
Deserialize an uint32_t from buffer
Parameters
buf Pointer to the uint32_t
Returns
The deserialized data
GET_UINT32() [2/4]
static uint32_t LittleEndian::GET_UINT32 (const uint8_t * buf, const int offset) inline static
Deserialize an uint32_t from buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer to access to an uint32_t* (in bytes)
Returns
The deserialized data
References GET_UINT32().
Referenced by GET_UINT32().
GET_UINT32() [3/4]
static uint32_t LittleEndian::GET_UINT32 (const char * buf) inline static
Deserialize an uint32_t from buffer
Parameters
buf Pointer to the uint32_t
Returns
The deserialized data
References GET_UINT32().
Referenced by GET_UINT32().
GET_UINT32() [4/4]
static uint32_t LittleEndian::GET_UINT32 (const char * buf, const int offset) inline static
Deserialize an uint32_t from buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer to access to an uint32_t* (in bytes)
Returns
The deserialized data
References GET_UINT32().
Referenced by GET_UINT32().
GET_UINT48() [1/4]
static uint64_t LittleEndian::GET_UINT48 (const uint8_t * buf) inline static
Deserialize an uint48_t from buffer.
Note
It is return on a uint64_t for conveniance
Parameters
buf Pointer to the uint48_t
Returns
The deserialized data
GET_UINT48() [2/4]
static uint64_t LittleEndian::GET_UINT48 (const uint8_t * buf, const int offset) inline static
Deserialize an uint48_t from buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer to access to an uint48_t* (in bytes)
Note
Store in a uint64_t for conveniance
Returns
The deserialized data
References GET_UINT48().
Referenced by GET_UINT48().
GET_UINT48() [3/4]
static uint64_t LittleEndian::GET_UINT48 (const char * buf) inline static
Deserialize an uint48_t from buffer.
Note
It is return on a uint64_t for conveniance
Parameters
buf Pointer to the uint48_t
Returns
The deserialized data
References GET_UINT48().
Referenced by GET_UINT48().
GET_UINT48() [4/4]
static uint64_t LittleEndian::GET_UINT48 (const char * buf, const int offset) inline static
Deserialize an uint48_t from buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer to access to an uint48_t* (in bytes)
Note
Store in a uint64_t for conveniance
Returns
The deserialized data
References GET_UINT48().
Referenced by GET_UINT48().
GET_UINT64() [1/4]
static uint64_t LittleEndian::GET_UINT64 (const uint8_t * buf) inline static
Deserialize an uint64_t from buffer
Parameters
buf Pointer to the uint64_t
Returns
The deserialized data
GET_UINT64() [2/4]
static uint64_t LittleEndian::GET_UINT64 (const uint8_t * buf, const int offset) inline static
Deserialize an uint64_t from buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer to access to an uint64_t* (in bytes)
Returns
The deserialized data
References GET_UINT64().
Referenced by GET_UINT64().
GET_UINT64() [3/4]
static uint64_t LittleEndian::GET_UINT64 (const char * buf) inline static
Deserialize an uint64_t from buffer
Parameters
buf Pointer to the uint64_t
Returns
The deserialized data
References GET_UINT64().
Referenced by GET_UINT64().
GET_UINT64() [4/4]
static uint64_t LittleEndian::GET_UINT64 (const char * buf, const int offset) inline static
Deserialize an uint64_t from buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer to access to an uint64_t* (in bytes)
Returns
The deserialized data
References GET_UINT64().
Referenced by GET_UINT64().
GET_UINT8() [1/4]
static uint8_t LittleEndian::GET_UINT8 (const uint8_t * buf) inline static
Deserialize an uint8_t from buffer
Parameters
buf Pointer to the uint8_t
Returns
The deserialized data
GET_UINT8() [2/4]
static uint8_t LittleEndian::GET_UINT8 (const uint8_t * buf, const int offset) inline static
Deserialize an uint8_t from buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer to access to an uint8_t* (in bytes)
Returns
The deserialized data
References GET_UINT8().
Referenced by GET_UINT8().
GET_UINT8() [3/4]
static uint8_t LittleEndian::GET_UINT8 (const char * buf) inline static
Deserialize an uint8_t from buffer
Parameters
buf Pointer to the uint8_t
Returns
The deserialized data
References GET_UINT8().
Referenced by GET_UINT8().
GET_UINT8() [4/4]
static uint8_t LittleEndian::GET_UINT8 (const char * buf, const int offset) inline static
Deserialize an uint8_t from buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer to access to an uint8_t* (in bytes)
Returns
The deserialized data
References GET_UINT8().
Referenced by GET_UINT8().
SET_FLOAT32() [1/6]
static void LittleEndian::SET_FLOAT32 (uint8_t * buf, const float val) inline static
Serialize a float in the buffer
Parameters
buf Pointer to the buffer
val Value to serialize
SET_FLOAT32() [2/6]
static void LittleEndian::SET_FLOAT32 (uint8_t * buf, const int offset, const float val) inline static
Serialize a float in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
val Value to serialize
References SET_FLOAT32().
Referenced by SET_FLOAT32().
SET_FLOAT32() [3/6]
static void LittleEndian::SET_FLOAT32 (uint8_t * buf, const int offset, const float val, int & length) inline static
Serialize a float in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
length Auto Increment this variable by the size of float
val Value to serialize
References SET_FLOAT32(), and LibEndian::UINT32_SIZE.
Referenced by SET_FLOAT32().
SET_FLOAT32() [4/6]
static void LittleEndian::SET_FLOAT32 (char * buf, const float val) inline static
Serialize a float in the buffer
Parameters
buf Pointer to the buffer
val Value to serialize
SET_FLOAT32() [5/6]
static void LittleEndian::SET_FLOAT32 (char * buf, const int offset, const float val) inline static
Serialize a float in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
val Value to serialize
References SET_FLOAT32().
Referenced by SET_FLOAT32().
SET_FLOAT32() [6/6]
static void LittleEndian::SET_FLOAT32 (char * buf, const int offset, const float val, int & length) inline static
Serialize a float in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
length Auto Increment this variable by the size of float
val Value to serialize
References SET_FLOAT32(), and LibEndian::UINT32_SIZE.
Referenced by SET_FLOAT32().
SET_FLOAT64() [1/6]
static void LittleEndian::SET_FLOAT64 (uint8_t * buf, const double val) inline static
Serialize a double in the buffer
Parameters
buf Pointer to the buffer
val Value to serialize
SET_FLOAT64() [2/6]
static void LittleEndian::SET_FLOAT64 (uint8_t * buf, const int offset, const double val) inline static
Serialize a double in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
val Value to serialize
References SET_FLOAT64().
Referenced by SET_FLOAT64().
SET_FLOAT64() [3/6]
static void LittleEndian::SET_FLOAT64 (uint8_t * buf, const int offset, const double val, int & length) inline static
Serialize a double in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
length Auto Increment this variable by the size of double
val Value to serialize
References SET_FLOAT64(), and LibEndian::UINT64_SIZE.
Referenced by SET_FLOAT64().
SET_FLOAT64() [4/6]
static void LittleEndian::SET_FLOAT64 (char * buf, const double val) inline static
Serialize a double in the buffer
Parameters
buf Pointer to the buffer
val Value to serialize
SET_FLOAT64() [5/6]
static void LittleEndian::SET_FLOAT64 (char * buf, const int offset, const double val) inline static
Serialize a double in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
val Value to serialize
References SET_FLOAT64().
Referenced by SET_FLOAT64().
SET_FLOAT64() [6/6]
static void LittleEndian::SET_FLOAT64 (char * buf, const int offset, const double val, int & length) inline static
Serialize a double in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
length Auto Increment this variable by the size of double
val Value to serialize
References SET_FLOAT64(), and LibEndian::UINT64_SIZE.
Referenced by SET_FLOAT64().
SET_INT16() [1/6]
static void LittleEndian::SET_INT16 (uint8_t * buf, const int16_t val) inline static
Serialize a int16_t in the buffer
Parameters
buf Pointer to the buffer
val Value to serialize
SET_INT16() [2/6]
static void LittleEndian::SET_INT16 (uint8_t * buf, const int offset, const int16_t val) inline static
Serialize a int16_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
val Value to serialize
References SET_INT16().
Referenced by SET_INT16().
SET_INT16() [3/6]
static void LittleEndian::SET_INT16 (uint8_t * buf, const int offset, const int16_t val, int & length) inline static
Serialize a int16_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
length Auto Increment this variable by the size of int16_t
val Value to serialize
References LibEndian::INT16_SIZE, and SET_INT16().
Referenced by SET_INT16().
SET_INT16() [4/6]
static void LittleEndian::SET_INT16 (char * buf, const int16_t val) inline static
Serialize a int16_t in the buffer
Parameters
buf Pointer to the buffer
val Value to serialize
SET_INT16() [5/6]
static void LittleEndian::SET_INT16 (char * buf, const int offset, const int16_t val) inline static
Serialize a int16_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
val Value to serialize
References SET_INT16().
Referenced by SET_INT16().
SET_INT16() [6/6]
static void LittleEndian::SET_INT16 (char * buf, const int offset, const int16_t val, int & length) inline static
Serialize a int16_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
length Auto Increment this variable by the size of int16_t
val Value to serialize
References LibEndian::INT16_SIZE, and SET_INT16().
Referenced by SET_INT16().
SET_INT32() [1/6]
static void LittleEndian::SET_INT32 (uint8_t * buf, const int32_t val) inline static
Serialize a int32_t in the buffer
Parameters
buf Pointer to the buffer
val Value to serialize
SET_INT32() [2/6]
static void LittleEndian::SET_INT32 (uint8_t * buf, const int offset, const int32_t val) inline static
Serialize a int32_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
val Value to serialize
References SET_INT32().
Referenced by SET_INT32().
SET_INT32() [3/6]
static void LittleEndian::SET_INT32 (uint8_t * buf, const int offset, const int32_t val, int & length) inline static
Serialize a int32_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
length Auto Increment this variable by the size of int32_t
val Value to serialize
References LibEndian::INT32_SIZE, and SET_INT32().
Referenced by SET_INT32().
SET_INT32() [4/6]
static void LittleEndian::SET_INT32 (char * buf, const int32_t val) inline static
Serialize a int32_t in the buffer
Parameters
buf Pointer to the buffer
val Value to serialize
SET_INT32() [5/6]
static void LittleEndian::SET_INT32 (char * buf, const int offset, const int32_t val) inline static
Serialize a int32_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
val Value to serialize
References SET_INT32().
Referenced by SET_INT32().
SET_INT32() [6/6]
static void LittleEndian::SET_INT32 (char * buf, const int offset, const int32_t val, int & length) inline static
Serialize a int32_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
length Auto Increment this variable by the size of int32_t
val Value to serialize
References LibEndian::INT32_SIZE, and SET_INT32().
Referenced by SET_INT32().
SET_INT48() [1/6]
static void LittleEndian::SET_INT48 (uint8_t * buf, const int64_t val) inline static
Serialize a int48 in the buffer
Parameters
buf Pointer to the buffer
val Value to serialize
Note
For conveniance the int48 is stored into a int64_t
SET_INT48() [2/6]
static void LittleEndian::SET_INT48 (uint8_t * buf, const int offset, const int64_t val) inline static
Serialize a int48_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
val Value to serialize
Note
For conveniance the int48 is stored into a int64_t
References SET_INT48().
Referenced by SET_INT48().
SET_INT48() [3/6]
static void LittleEndian::SET_INT48 (uint8_t * buf, const int offset, const int64_t val, int & length) inline static
Serialize a int48_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
length Auto Increment this variable by the size of int48_t
Note
For conveniance the int48 is stored into a int64_t
Parameters
val Value to serialize
References LibEndian::INT48_SIZE, and SET_INT48().
Referenced by SET_INT48().
SET_INT48() [4/6]
static void LittleEndian::SET_INT48 (char * buf, const int64_t val) inline static
Serialize a int48 in the buffer
Parameters
buf Pointer to the buffer
val Value to serialize
Note
For conveniance the int48 is stored into a int64_t
SET_INT48() [5/6]
static void LittleEndian::SET_INT48 (char * buf, const int offset, const int64_t val) inline static
Serialize a int48_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
val Value to serialize
Note
For conveniance the int48 is stored into a int64_t
References SET_INT48().
Referenced by SET_INT48().
SET_INT48() [6/6]
static void LittleEndian::SET_INT48 (char * buf, const int offset, const int64_t val, int & length) inline static
Serialize a int48_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
length Auto Increment this variable by the size of int48_t
Note
For conveniance the int48 is stored into a int64_t
Parameters
val Value to serialize
References LibEndian::INT48_SIZE, and SET_INT48().
Referenced by SET_INT48().
SET_INT64() [1/6]
static void LittleEndian::SET_INT64 (uint8_t * buf, const int64_t val) inline static
Serialize a int64_t in the buffer
Parameters
buf Pointer to the buffer
val Value to serialize
SET_INT64() [2/6]
static void LittleEndian::SET_INT64 (uint8_t * buf, const int offset, const int64_t val) inline static
Serialize a int64_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
val Value to serialize
References SET_INT64().
Referenced by SET_INT64().
SET_INT64() [3/6]
static void LittleEndian::SET_INT64 (uint8_t * buf, const int offset, const int64_t val, int & length) inline static
Serialize a int64_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
length Auto Increment this variable by the size of int64_t
val Value to serialize
References LibEndian::INT64_SIZE, and SET_INT64().
Referenced by SET_INT64().
SET_INT64() [4/6]
static void LittleEndian::SET_INT64 (char * buf, const int64_t val) inline static
Serialize a int64_t in the buffer
Parameters
buf Pointer to the buffer
val Value to serialize
SET_INT64() [5/6]
static void LittleEndian::SET_INT64 (char * buf, const int offset, const int64_t val) inline static
Serialize a int64_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
val Value to serialize
References SET_INT64().
Referenced by SET_INT64().
SET_INT64() [6/6]
static void LittleEndian::SET_INT64 (char * buf, const int offset, const int64_t val, int & length) inline static
Serialize a int64_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
length Auto Increment this variable by the size of int64_t
val Value to serialize
References LibEndian::INT64_SIZE, and SET_INT64().
Referenced by SET_INT64().
SET_INT8() [1/6]
static void LittleEndian::SET_INT8 (uint8_t * buf, const int8_t val) inline static
Serialize a int8_t in the buffer
Parameters
buf Pointer to the buffer
val Value to serialize
SET_INT8() [2/6]
static void LittleEndian::SET_INT8 (uint8_t * buf, const int offset, const int8_t val) inline static
Serialize a int8_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
val Value to serialize
References SET_INT8().
Referenced by SET_INT8().
SET_INT8() [3/6]
static void LittleEndian::SET_INT8 (uint8_t * buf, const int offset, const int8_t val, int & length) inline static
Serialize a int8_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
length Auto Increment this variable by the size of int8_t
val Value to serialize
References LibEndian::INT8_SIZE, and SET_INT8().
Referenced by SET_INT8().
SET_INT8() [4/6]
static void LittleEndian::SET_INT8 (char * buf, const int8_t val) inline static
Serialize a int8_t in the buffer
Parameters
buf Pointer to the buffer
val Value to serialize
SET_INT8() [5/6]
static void LittleEndian::SET_INT8 (char * buf, const int offset, const int8_t val) inline static
Serialize a int8_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
val Value to serialize
References SET_INT8().
Referenced by SET_INT8().
SET_INT8() [6/6]
static void LittleEndian::SET_INT8 (char * buf, const int offset, const int8_t val, int & length) inline static
Serialize a int8_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
length Auto Increment this variable by the size of int8_t
val Value to serialize
References LibEndian::INT8_SIZE, and SET_INT8().
Referenced by SET_INT8().
SET_UINT16() [1/6]
static void LittleEndian::SET_UINT16 (uint8_t * buf, const uint16_t val) inline static
Serialize a uint16_t in the buffer
Parameters
buf Pointer to the buffer
val Value to serialize
SET_UINT16() [2/6]
static void LittleEndian::SET_UINT16 (uint8_t * buf, const int offset, const uint16_t val) inline static
Serialize a uint16_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
val Value to serialize
References SET_UINT16().
Referenced by SET_UINT16().
SET_UINT16() [3/6]
static void LittleEndian::SET_UINT16 (uint8_t * buf, const int offset, const uint16_t val, int & length) inline static
Serialize a uint16_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
length Auto Increment this variable by the size of uint16_t
val Value to serialize
References SET_UINT16(), and LibEndian::UINT16_SIZE.
Referenced by SET_UINT16().
SET_UINT16() [4/6]
static void LittleEndian::SET_UINT16 (char * buf, const uint16_t val) inline static
Serialize a uint16_t in the buffer
Parameters
buf Pointer to the buffer
val Value to serialize
References SET_UINT16().
Referenced by SET_UINT16().
SET_UINT16() [5/6]
static void LittleEndian::SET_UINT16 (char * buf, const int offset, const uint16_t val) inline static
Serialize a uint16_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
val Value to serialize
References SET_UINT16().
Referenced by SET_UINT16().
SET_UINT16() [6/6]
static void LittleEndian::SET_UINT16 (char * buf, const int offset, const uint16_t val, int & length) inline static
Serialize a uint16_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
length Auto Increment this variable by the size of uint16_t
val Value to serialize
References SET_UINT16(), and LibEndian::UINT16_SIZE.
Referenced by SET_UINT16().
SET_UINT32() [1/6]
static void LittleEndian::SET_UINT32 (uint8_t * buf, const uint32_t val) inline static
Serialize a uint32_t in the buffer
Parameters
buf Pointer to the buffer
val Value to serialize
SET_UINT32() [2/6]
static void LittleEndian::SET_UINT32 (uint8_t * buf, const int offset, const uint32_t val) inline static
Serialize a uint32_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
val Value to serialize
References SET_UINT32().
Referenced by SET_UINT32().
SET_UINT32() [3/6]
static void LittleEndian::SET_UINT32 (uint8_t * buf, const int offset, const uint32_t val, int & length) inline static
Serialize a uint32_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
length Auto Increment this variable by the size of uint32_t
val Value to serialize
References SET_UINT32(), and LibEndian::UINT32_SIZE.
Referenced by SET_UINT32().
SET_UINT32() [4/6]
static void LittleEndian::SET_UINT32 (char * buf, const uint32_t val) inline static
Serialize a uint32_t in the buffer
Parameters
buf Pointer to the buffer
val Value to serialize
References SET_UINT32().
Referenced by SET_UINT32().
SET_UINT32() [5/6]
static void LittleEndian::SET_UINT32 (char * buf, const int offset, const uint32_t val) inline static
Serialize a uint32_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
val Value to serialize
References SET_UINT32().
Referenced by SET_UINT32().
SET_UINT32() [6/6]
static void LittleEndian::SET_UINT32 (char * buf, const int offset, const uint32_t val, int & length) inline static
Serialize a uint32_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
length Auto Increment this variable by the size of uint32_t
val Value to serialize
References SET_UINT32(), and LibEndian::UINT32_SIZE.
Referenced by SET_UINT32().
SET_UINT48() [1/6]
static void LittleEndian::SET_UINT48 (uint8_t * buf, const uint64_t val) inline static
Serialize a uint48_t in the buffer
Parameters
buf Pointer to the buffer
val Value to serialize
Note
For conveniance the uint48 is stored into a uint64_t
SET_UINT48() [2/6]
static void LittleEndian::SET_UINT48 (uint8_t * buf, const int offset, const uint64_t val) inline static
Serialize a uint48_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
val Value to serialize
Note
For conveniance the uint48 is stored into a uint64_t
References SET_UINT48().
Referenced by SET_UINT48().
SET_UINT48() [3/6]
static void LittleEndian::SET_UINT48 (uint8_t * buf, const int offset, const uint64_t val, int & length) inline static
Serialize a uint48_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
length Auto Increment this variable by the size of uint48_t
Note
For conveniance the uint48 is stored into a uint64_t
Parameters
val Value to serialize
References SET_UINT48(), and LibEndian::UINT48_SIZE.
Referenced by SET_UINT48().
SET_UINT48() [4/6]
static void LittleEndian::SET_UINT48 (char * buf, const uint64_t val) inline static
Serialize a uint48_t in the buffer
Parameters
buf Pointer to the buffer
val Value to serialize
Note
For conveniance the uint48 is stored into a uint64_t
References SET_UINT48().
Referenced by SET_UINT48().
SET_UINT48() [5/6]
static void LittleEndian::SET_UINT48 (char * buf, const int offset, const uint64_t val) inline static
Serialize a uint48_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
val Value to serialize
Note
For conveniance the uint48 is stored into a uint64_t
References SET_UINT48().
Referenced by SET_UINT48().
SET_UINT48() [6/6]
static void LittleEndian::SET_UINT48 (char * buf, const int offset, const uint64_t val, int & length) inline static
Serialize a uint48_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
length Auto Increment this variable by the size of uint48_t
Note
For conveniance the uint48 is stored into a uint64_t
Parameters
val Value to serialize
References SET_UINT48(), and LibEndian::UINT48_SIZE.
Referenced by SET_UINT48().
SET_UINT64() [1/6]
static void LittleEndian::SET_UINT64 (uint8_t * buf, const uint64_t val) inline static
Serialize a uint64_t in the buffer
Parameters
buf Pointer to the buffer
val Value to serialize
SET_UINT64() [2/6]
static void LittleEndian::SET_UINT64 (uint8_t * buf, const int offset, const uint64_t val) inline static
Serialize a uint64_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
val Value to serialize
References SET_UINT64().
Referenced by SET_UINT64().
SET_UINT64() [3/6]
static void LittleEndian::SET_UINT64 (uint8_t * buf, const int offset, const uint64_t val, int & length) inline static
Serialize a uint64_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
length Auto Increment this variable by the size of uint64_t
val Value to serialize
References SET_UINT64(), and LibEndian::UINT64_SIZE.
Referenced by SET_UINT64().
SET_UINT64() [4/6]
static void LittleEndian::SET_UINT64 (char * buf, const uint64_t val) inline static
Serialize a uint64_t in the buffer
Parameters
buf Pointer to the buffer
val Value to serialize
References SET_UINT64().
Referenced by SET_UINT64().
SET_UINT64() [5/6]
static void LittleEndian::SET_UINT64 (char * buf, const int offset, const uint64_t val) inline static
Serialize a uint64_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
val Value to serialize
References SET_UINT64().
Referenced by SET_UINT64().
SET_UINT64() [6/6]
static void LittleEndian::SET_UINT64 (char * buf, const int offset, const uint64_t val, int & length) inline static
Serialize a uint64_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
length Auto Increment this variable by the size of uint64_t
val Value to serialize
References SET_UINT64(), and LibEndian::UINT64_SIZE.
Referenced by SET_UINT64().
SET_UINT8() [1/6]
static void LittleEndian::SET_UINT8 (uint8_t * buf, const uint8_t val) inline static
Serialize a uint8_t in the buffer
Parameters
buf Pointer to the buffer
val Value to serialize
SET_UINT8() [2/6]
static void LittleEndian::SET_UINT8 (uint8_t * buf, const int offset, const uint8_t val) inline static
Serialize a uint8_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
val Value to serialize
References SET_UINT8().
Referenced by SET_UINT8().
SET_UINT8() [3/6]
static void LittleEndian::SET_UINT8 (uint8_t * buf, const int offset, const uint8_t val, int & length) inline static
Serialize a uint8_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
length Auto Increment this variable by the size of uint8_t
val Value to serialize
References SET_UINT8(), and LibEndian::UINT8_SIZE.
Referenced by SET_UINT8().
SET_UINT8() [4/6]
static void LittleEndian::SET_UINT8 (char * buf, const uint8_t val) inline static
Serialize a uint8_t in the buffer
Parameters
buf Pointer to the buffer
val Value to serialize
References SET_UINT8().
Referenced by SET_UINT8().
SET_UINT8() [5/6]
static void LittleEndian::SET_UINT8 (char * buf, const int offset, const uint8_t val) inline static
Serialize a uint8_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
val Value to serialize
References SET_UINT8().
Referenced by SET_UINT8().
SET_UINT8() [6/6]
static void LittleEndian::SET_UINT8 (char * buf, const int offset, const uint8_t val, int & length) inline static
Serialize a uint8_t in the buffer
Parameters
buf Pointer to the buffer
offset Offset in the buffer (in bytes)
length Auto Increment this variable by the size of uint8_t
val Value to serialize
References SET_UINT8(), and LibEndian::UINT8_SIZE.
Referenced by SET_UINT8().
The documentation for this class was generated from the following file:
LittleEndian.hpp